# Generated by Django 3.0.7 on 2021-07-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminHOD',
            new_name='HOD',
        ),
    ]
