# Generated by Django 3.0.7 on 2021-07-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_adminhod_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='session_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.SessionYearModel'),
        ),
    ]
