# Generated by Django 3.0.7 on 2021-06-15 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_onlineclassroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('title_tag', models.CharField(default='Ashis Blog', max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('body', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='coding', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
