# Generated by Django 3.0.7 on 2021-06-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_post_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contribution',
        ),
        migrations.DeleteModel(
            name='Post_category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
