# Generated by Django 3.0.7 on 2021-07-17 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20210717_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='staff',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
