# Generated by Django 3.0.7 on 2021-07-19 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_assignment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='dept_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_dept', to='student_management_app.Department'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='dept_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_dept', to='student_management_app.Department'),
        ),
        migrations.AlterField(
            model_name='students',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_dept', to='student_management_app.Department'),
        ),
    ]
