# Generated by Django 3.0.7 on 2021-10-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(0, 'Principal'), (1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=0, max_length=10),
        ),
    ]
