# Generated by Django 3.0.7 on 2021-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211009_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Principal'), (1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=0),
        ),
    ]
